version: '3'

services:
  db:
    container_name: app_db
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=app
      - MYSQL_PASSWORD=password123
      - MYSQL_DATABASE=app_development
    ports:
      - 3306:3306
  backend:
    container_name: backend
    build: .
    image: image_back
    command: rails s --binding=0.0.0.0
    entrypoint: ./scripts/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - db
  frontend:
    container_name: frontend
    build: ./client
    image: image_front
    command: npm start -s
    entrypoint: ./scripts/entrypoint.sh
    volumes:
      - ./:/app
    depends_on:
      - backend
    ports:
      - 8080:8080
    environment:
      NODE_ENV: development
